### ISSUE TITLE
Unable to minify

### ISSUE THREAD

**Issue by dmiko** [angular/ts-minify#60]
Hello,

I'm looking for minify tool which can obfuscate whole my project.
I need to rename all variables, methods, properties and classes names (including "export" ones).

I'm trying to use ts-minify but currently have these problem:

1) "Symbol information could not be extracted" 
I have this error near:
```
export function x(let el: Element) {
el.className = "xx"; // here
}
```
do I need to load ES5 library for ts-minify?

2) If I set fastFail to false, error (1) goes out (!) but I see another error:
"Error: ts-minify does not support accepting both internal and external types at a use site
Symbol name: Dialog"

I have class Dialog:

```
export class Dialog {
..
}
```

and use it in this way (in other files):

`import {Dialog} from "dir/dialog"`

What am I doing wrong? TSC sees no problems in such code.

3) Exports are not being renamed...
I pass all linked to each other files as one array to renameProgram() method, so I expect ts-minify knows anything about classes and can rename them in all the files.
I want to rename anything except one API class I specify (and its public methods). All other classes are internal, tough they have "export" keyword. 
How to pass API class name to ts-minify and let ts-minify to rename everything except it?

I will be very appreciated for any help :)

**Comment by mprobst** [comment]
Hi. This project was a bit of a tech demo/try out, but never quite made it to seaworthiness.

@alexeagle has been busy adding bits and pieces to https://github.com/angular/tsickle and https://github.com/angular/angular. Alex, what was the tracking issue for this again?

**Comment by alexeagle** [comment]
@mprobst maybe you're referring to https://github.com/angular/angular/issues/8550 ?

**Comment by mprobst** [comment]
Yep, that's it.

**Comment by dmiko** [comment]
@mprobst , thank you for answer.
How do you think is it even possible to implement what I need (item 3) with TypeScript API?
I'm thinking about to start from ts-minify and upgrade it for my needs or to write my own tool.

**Comment by mprobst** [comment]
@dmiko the TS API is pretty complete, with enough effort you can probably make this work. I'm not sure though if that's the simplest solution, I'd rather look into `tsickle`.
